name: Python checks

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  lint-format-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        qt-version: [qt5, qt6]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/dev.txt -r ./requirements/anki-${{ matrix.qt-version }}.txt

      - name: Black
        run: black src --check

      - name: Flake8
        run: flake8 src

      - name: isort
        run: isort src -c

      - name: Mypy
        run: mypy src
